type RecordValue=Record<string,any>;
export type Segment={departureAirport:{id:string;name:string;time:string};arrivalAirport:{id:string;name:string;time:string};durationMinutes:number;airplane?:string;airline?:string;airlineLogo?:string;travelClass?:string;flightNumber?:string;legroom?:string;amenities:string[];overnight?:boolean;oftenDelayedByOver30Min?:boolean;operatedBy?:string};
export type NormalizedCashOffer={id:string;resultGroup:'best'|'other';provider:string;price:number;currency:string;totalDurationMinutes:number;stops:number;isDirect:boolean;isOvernight:boolean;hasDelayWarning:boolean;mainAirline?:string;mainAirlineLogo?:string;layovers:{id:string;name:string;durationMinutes:number}[];carbon?:{grams?:number;typicalGrams?:number;differencePercent?:number};departureToken?:string;bookingToken?:string;requiresReturnSelection:boolean;requiresRevalidation:true;googleFlightsUrl?:string;segments:Segment[];extensions:string[];dealScore?:number;dealLabel?:string;discountPercent?:number};
export type NormalizedFlightSearch={source:'serpapi_google_flights';searchMetadata:RecordValue;search:RecordValue;route:RecordValue;priceInsights?:RecordValue;offers:NormalizedCashOffer[]};
const object=(x:unknown):RecordValue|undefined=>x&&typeof x==='object'&&!Array.isArray(x)?x as RecordValue:undefined;
export function unwrapFlightSearchResponse(input:unknown):unknown{let current=input;for(let i=0;i<8;i++){if(Array.isArray(current)&&current.length===1){current=current[0];continue}const record=object(current);if(record?.response!==undefined){current=record.response;continue}if(record?.data!==undefined){current=record.data;continue}break}return current}
export function isN8nCashSearchEnvelope(value:unknown):boolean{const r=object(value);return r?.ok===true&&Array.isArray(r.offers)&&typeof r.provider==='string'&&!!r.query}
export function isRawSerpApiResponse(value:unknown):boolean{const r=object(value);return Boolean(r&&(Array.isArray(r.best_flights)||Array.isArray(r.other_flights))&&r.search_parameters)}
const history=(p:any)=>Array.isArray(p?.price_history)?p.price_history.map(([timestamp,price]:[number,number])=>({timestamp,date:new Date(timestamp*1000).toISOString(),price})):[];
function segment(s:any):Segment{return{departureAirport:{id:s.origin??s.departure_airport?.id??'',name:s.origin??s.departure_airport?.name??'',time:s.departureTime??s.departure_airport?.time??''},arrivalAirport:{id:s.destination??s.arrival_airport?.id??'',name:s.destination??s.arrival_airport?.name??'',time:s.arrivalTime??s.arrival_airport?.time??''},durationMinutes:s.durationMinutes??s.duration??0,airplane:s.aircraft??s.airplane,airline:s.airline,airlineLogo:s.airlineLogo??s.airline_logo,travelClass:s.travelClass??s.travel_class,flightNumber:s.flightNumber??s.flight_number,legroom:s.legroom,amenities:s.amenities??s.extensions??[],overnight:s.overnight??false,oftenDelayedByOver30Min:s.oftenDelayed??s.often_delayed_by_over_30_min??false,operatedBy:s.operatedBy??s.plane_and_crew_by}}
function offer(o:any,index:number,group:'best'|'other',currency:string,url?:string):NormalizedCashOffer{const segments:Segment[]=(o.segments??o.flights??[]).map(segment);const carbon=o.carbonEmissions??o.carbon_emissions;return{id:o.fingerprint??`${group}-${index}-${o.price}`,resultGroup:o.resultGroup??group,provider:o.provider??'serpapi_google_flights',price:o.price??0,currency:o.currency??currency,totalDurationMinutes:o.totalDurationMinutes??o.total_duration??0,stops:o.stops??Math.max(0,segments.length-1),isDirect:(o.stops??Math.max(0,segments.length-1))===0,isOvernight:segments.some((x:Segment)=>x.overnight),hasDelayWarning:segments.some((x:Segment)=>x.oftenDelayedByOver30Min),mainAirline:o.airline??segments[0]?.airline,mainAirlineLogo:o.airlineLogo??o.airline_logo??segments[0]?.airlineLogo,layovers:(o.layovers??[]).map((x:any)=>({id:x.id,name:x.name,durationMinutes:x.durationMinutes??x.duration??0})),carbon:carbon?{grams:carbon.this_flight,typicalGrams:carbon.typical_for_this_route,differencePercent:carbon.difference_percent}:undefined,departureToken:o.departureToken??o.departure_token,bookingToken:o.bookingToken??o.booking_token,requiresReturnSelection:Boolean(o.departureToken??o.departure_token),requiresRevalidation:true,googleFlightsUrl:o.sourceUrl??url,segments,extensions:segments.flatMap((x:Segment)=>x.amenities),dealScore:o.dealScore,dealLabel:o.dealLabel,discountPercent:o.discountPercent}}
function n8n(e:any):NormalizedFlightSearch{const pi=e.priceInsights;return{source:'serpapi_google_flights',searchMetadata:{id:e.searchId,processedAt:e.fetchedAt},search:{origin:e.query.origin,destination:e.query.destination,outboundDate:e.query.departureDate,returnDate:e.query.returnDate,currency:e.query.currency??'BRL'},route:{},priceInsights:pi?{lowestPrice:pi.lowest_price,priceLevel:pi.price_level,typicalLow:pi.typical_price_range?.[0],typicalHigh:pi.typical_price_range?.[1],history:history(pi)}:undefined,offers:e.offers.map((x:any,i:number)=>offer(x,i,i===0?'best':'other',e.query.currency??'BRL',x.sourceUrl))}}
function raw(r:any):NormalizedFlightSearch{const p=r.search_parameters,pi=r.price_insights,meta=r.search_metadata;return{source:'serpapi_google_flights',searchMetadata:{id:meta?.id,processedAt:meta?.processed_at,googleFlightsUrl:meta?.google_flights_url},search:{origin:p.departure_id,destination:p.arrival_id,outboundDate:p.outbound_date,returnDate:p.return_date,currency:p.currency??'BRL'},route:r.airports?.[0]??{},priceInsights:pi?{lowestPrice:pi.lowest_price,priceLevel:pi.price_level,typicalLow:pi.typical_price_range?.[0],typicalHigh:pi.typical_price_range?.[1],history:history(pi)}:undefined,offers:[...(r.best_flights??[]).map((x:any,i:number)=>offer(x,i,'best',p.currency,meta?.google_flights_url)),...(r.other_flights??[]).map((x:any,i:number)=>offer(x,i,'other',p.currency,meta?.google_flights_url))]}}
export function normalizeSerpApiFlightsResponse(input:unknown):NormalizedFlightSearch{const root=unwrapFlightSearchResponse(input);if(isN8nCashSearchEnvelope(root))return n8n(root);if(isRawSerpApiResponse(root))return raw(root);return{source:'serpapi_google_flights',searchMetadata:{},search:{},route:{},offers:[]}}
