import { z } from 'zod';

const airport = z.string().trim().toUpperCase().regex(/^[A-Z]{3}(,[A-Z]{3})*$/, 'Use códigos IATA separados por vírgula');
const date = z.string().date();
export const searchSchema = z.object({ origin: airport, destination: airport, departureDate: date, returnDate: date.optional(), adults: z.number().int().min(1).max(9), children: z.number().int().min(0).max(9).optional(), infantsInSeat: z.number().int().min(0).max(9).optional(), infantsOnLap: z.number().int().min(0).max(9).optional(), cabin: z.enum(['economy','premium_economy','business','first']), stops: z.enum(['any','nonstop','one_or_less','two_or_less']), maxPrice: z.number().positive().optional(), maxDuration: z.number().int().positive().optional(), currency: z.string().length(3).optional(), gl: z.string().length(2).optional(), hl: z.string().min(2).max(5).optional(), deepSearch: z.boolean().optional(), mode: z.enum(['cash','awards','compare']).optional() }).refine(v => !v.returnDate || v.returnDate >= v.departureDate, { message: 'Retorno deve ser posterior à ida', path: ['returnDate'] });
export const awardsSchema = z.object({ origin: airport, destination: airport, startDate: date, endDate: date, sources: z.array(z.string()).optional(), cabins: z.array(z.string()).optional(), onlyDirect: z.boolean().optional(), take: z.number().int().min(1).max(100).optional() });
export const dealsSchema = z.object({ origin: airport, cabin: z.enum(['economy','premium_economy','business','first']).optional(), maxPrice: z.number().positive().optional(), adults: z.number().int().min(1).max(9).optional(), departureDate: date.optional(), returnDate: date.optional(), tripType: z.enum(['one_way','round_trip']).optional() });
export const trendsSchema = z.object({ origin: airport, destination: airport.optional(), currency: z.string().length(3).optional(), periodType: z.string().optional(), limit: z.number().int().min(1).max(100).optional(), sorting: z.string().optional(), tripClass: z.number().int().min(0).max(3).optional() });
export type SearchInput = z.infer<typeof searchSchema>;
