import http from 'node:http';
import { azul } from './providers/azul.js'; import { latam } from './providers/latam.js'; import { smiles } from './providers/smiles.js';
import { errorArtifacts, profile, type Program, type Provider, type Search } from './providers/base.js';
const providers: Record<Program, Provider> = { latam_pass: latam, smiles, azul_fidelidade: azul };
const enabled: Record<Program, string> = { latam_pass: 'LATAM_SCRAPER_ENABLED', smiles: 'SMILES_SCRAPER_ENABLED', azul_fidelidade: 'AZUL_SCRAPER_ENABLED' };
function body(req: http.IncomingMessage) { return new Promise<Record<string, unknown>>(resolve => { let raw = ''; req.on('data', c => raw += c); req.on('end', () => { try { resolve(JSON.parse(raw || '{}')); } catch { resolve({}); } }); }); }
function programOf(value: unknown): Program | undefined { return value === 'latam_pass' || value === 'smiles' || value === 'azul_fidelidade' ? value : undefined; }
const server = http.createServer(async (req, res) => { res.setHeader('content-type', 'application/json'); const input = await body(req); const program = programOf(input.program); if (req.url === '/health') { res.end(JSON.stringify({ status: 'ok', service: 'award-scraper', enabled: Object.fromEntries(Object.entries(enabled).map(([key, env]) => [key, process.env[env] === 'true'])) })); return; } if (!program) { res.statusCode = 400; res.end(JSON.stringify({ error: 'Programa inválido' })); return; } if (process.env[enabled[program]] !== 'true') { res.statusCode = 503; res.end(JSON.stringify({ state: 'temporarily_unavailable', error: 'Programa desativado' })); return; } const provider = providers[program]; const context = await profile(program); if (req.url === '/v1/session/start') { const page = context.pages()[0] ?? await context.newPage(); await page.goto(provider.loginUrl, { waitUntil: 'domcontentloaded' }); res.end(JSON.stringify({ state: 'login_required', reloginUrl: provider.loginUrl, message: 'Conclua o login manual no perfil aberto. Senhas, CAPTCHA e MFA não são automatizados.' })); return; } const valid = await provider.sessionValid(context); if (req.url === '/v1/session/status') { res.end(JSON.stringify({ program, enabled: true, authenticated: valid, sessionExpired: !valid, reloginUrl: valid ? undefined : provider.loginUrl })); return; } if (req.url !== '/v1/award/search') { res.statusCode = 404; res.end(JSON.stringify({ error: 'Não encontrado' })); return; } if (!valid) { res.statusCode = 401; res.end(JSON.stringify({ state: 'session_expired', reloginUrl: provider.loginUrl })); return; } const page = context.pages()[0] ?? await context.newPage(); try { const offers = await provider.search(context, input as unknown as Search); res.end(JSON.stringify({ state: 'received', offers })); } catch (error) { await errorArtifacts(program, page); res.statusCode = 502; res.end(JSON.stringify({ state: 'temporarily_unavailable', error: error instanceof Error ? error.message : 'Falha no navegador' })); } });
server.listen(Number(process.env.PORT ?? 3001));
